# Generated by Django 3.1.2 on 2020-11-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personal_Info',
            fields=[
                ('pi_pk', models.AutoField(primary_key=True, serialize=False)),
                ('sur_name', models.CharField(max_length=75)),
                ('first_name', models.CharField(max_length=75)),
                ('middle_name', models.CharField(blank=True, max_length=75, null=True)),
                ('name_ext', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField()),
                ('pace_of_birth', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=10)),
                ('civil_status', models.CharField(max_length=15)),
                ('height', models.CharField(max_length=15)),
                ('weight', models.CharField(max_length=15)),
                ('blood_type', models.CharField(max_length=5)),
                ('gsis_id_no', models.IntegerField(default=0)),
                ('pagibig_id_no', models.IntegerField(default=0)),
                ('philhealth_no', models.IntegerField(default=0)),
                ('sss_no', models.IntegerField(default=0)),
                ('tin_no', models.IntegerField(default=0)),
                ('agency_employee_no', models.IntegerField(default=0)),
                ('citizenship', models.CharField(max_length=100)),
                ('citizenship_country', models.CharField(max_length=100)),
                ('res_lot_no', models.CharField(max_length=20)),
                ('res_street', models.CharField(max_length=75)),
                ('res_subd', models.CharField(max_length=50)),
                ('res_brgy', models.CharField(max_length=50)),
                ('res_city', models.CharField(max_length=50)),
                ('res_province', models.CharField(max_length=50)),
                ('res_reg', models.CharField(max_length=50)),
                ('res_zipcode', models.IntegerField()),
                ('per_lot_no', models.CharField(max_length=20)),
                ('per_street', models.CharField(max_length=75)),
                ('per_subd', models.CharField(max_length=50)),
                ('per_brgy', models.CharField(max_length=50)),
                ('per_city', models.CharField(max_length=50)),
                ('per_province', models.CharField(max_length=50)),
                ('per_reg', models.CharField(max_length=50)),
                ('per_zipcode', models.IntegerField()),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_no', models.IntegerField()),
                ('email_address', models.EmailField(blank=True, max_length=75, null=True)),
                ('photo', models.CharField(blank=True, max_length=100, null=True)),
                ('date_accomplished', models.DateField()),
            ],
        ),
    ]
