# Generated by Django 3.1.2 on 2020-11-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='refbrgy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('psgcCode', models.CharField(max_length=255)),
                ('regCode', models.CharField(max_length=255)),
                ('citymunDesc', models.TextField()),
                ('provCode', models.CharField(max_length=255)),
                ('citymunCode', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='refcitymun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('psgcCode', models.CharField(max_length=255)),
                ('citymunDesc', models.TextField()),
                ('provCode', models.CharField(max_length=255)),
                ('citymunCode', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='refprovince',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('psgcCode', models.CharField(max_length=255)),
                ('provDesc', models.TextField()),
                ('regCode', models.CharField(max_length=255)),
                ('provCode', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='sex',
            field=models.CharField(choices=[(0, 'Male'), (1, 'Female')], max_length=10),
        ),
    ]
