# Generated by Django 3.1.2 on 2020-11-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_auto_20201127_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='agency_employee_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='gsis_id_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='pagibig_id_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='philhealth_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='sss_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='tin_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
