# Generated by Django 3.1.2 on 2020-12-03 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0004_auto_20201127_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='family_Background',
            fields=[
                ('fb_pk', models.AutoField(primary_key=True, serialize=False)),
                ('spouse_sur_name', models.CharField(blank=True, max_length=75, null=True)),
                ('spouse_first_name', models.CharField(blank=True, max_length=75, null=True)),
                ('spouse_middle_name', models.CharField(blank=True, max_length=75, null=True)),
                ('spouse_name_ext', models.CharField(blank=True, max_length=20, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('business_name', models.CharField(blank=True, max_length=150, null=True)),
                ('business_address', models.CharField(blank=True, max_length=200, null=True)),
                ('spouse_telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('father_sur_name', models.CharField(max_length=75)),
                ('father_first_name', models.CharField(max_length=75)),
                ('father_middle_name', models.CharField(blank=True, max_length=75, null=True)),
                ('father_name_ext', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_sur_name', models.CharField(max_length=75)),
                ('mother_first_name', models.CharField(max_length=75)),
                ('mother_middle_name', models.CharField(blank=True, max_length=75, null=True)),
                ('fb_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apply.personal_info')),
            ],
        ),
    ]
