# Generated by Django 3.1.2 on 2020-12-15 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0006_auto_20201204_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='ref_barangay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brgyCode', models.CharField(max_length=50, unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'Barangay',
                'verbose_name_plural': 'Barangays',
            },
        ),
        migrations.CreateModel(
            name='ref_region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('psgcCode', models.CharField(max_length=50, unique=True)),
                ('name', models.TextField()),
                ('regCode', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='ref_purok',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('president', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ref_barangay_id', to='apply.ref_barangay')),
            ],
        ),
        migrations.CreateModel(
            name='ref_province',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('psgcCode', models.CharField(max_length=50, unique=True)),
                ('name', models.TextField()),
                ('provCode', models.CharField(max_length=50, unique=True)),
                ('f_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apply.ref_region', to_field='regCode')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ref_region_id', to='apply.ref_region')),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
            },
        ),
        migrations.CreateModel(
            name='ref_citymun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('psgcCode', models.CharField(max_length=50, unique=True)),
                ('name', models.TextField()),
                ('citymunCode', models.CharField(max_length=50, unique=True)),
                ('f_province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apply.ref_province', to_field='provCode')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ref_province_id', to='apply.ref_province')),
            ],
            options={
                'verbose_name': 'City/Municipality',
                'verbose_name_plural': 'Cities and Municipalities',
            },
        ),
        migrations.AddField(
            model_name='ref_barangay',
            name='citymun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ref_citymun_id', to='apply.ref_citymun'),
        ),
        migrations.AddField(
            model_name='ref_barangay',
            name='f_citymun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apply.ref_citymun', to_field='citymunCode'),
        ),
    ]
